### ISSUE TITLE
Can't build a cloned language

### ISSUE THREAD

**Issue by kristiank** [GrammaticalFramework/gf-rgl#2]
I can't build a language if I clone it from an existing language. For instance, if I run `Clone.hs` (being in the 'src' folder):
```shell
$ runghc Clone.hs estonian votic Est Vot
```
and then run the `Make.hs` (being in the top folder):
```shell
runghc Make.hs build --langs=Vot
```
I get the following output:
```shell
Compiling [prelude]
Compiling [AllTenses] src/*/All*.gf src/*/Symbol*.gf src/*/Compatibility*.gf src/api/Try*.gf src/api/Symbolic*.gf
No input files.
Ran: gf -batch -gf-lib-path=src -s -no-pmcfg --gfo-dir=dist/alltenses
gf exited with exit code: 1
```

I have tried cloning from several source languages with no output difference. Is the `src/Clone.hs` program deprecated?

**Comment by johnjcamilleri** [comment]
Thanks for this Kristian. Clone.hs *should* be considered current and not
deprecated. The reason for this issue is that the script is generic to any
directory containing .gf files, but in order to get a compilable resource
grammar a few more extra files in src/api are needed.
These other files can easily be created manually, but I will work on a fix
for this soon.

John

**Comment by kristiank** [comment]
Thanks. Is only the `src/api/Try*.gf` and `src/api/Symbolic*.gf` files needed? I tried manually cloning (e.g copying and renaming) all of the relevant language's files in `src/api` and changing their contents according to the new target language. Still I get the same output. My `dist` folder looks like this after the unsuccessful build:

```bash
$ ls -R dist/
dist/:
alltenses  prelude

dist/alltenses:

dist/prelude:
Coordination.gfo  HTML.gfo   Maybe.gfo       PredefAbs.gfo  Predef.gfo
Formal.gfo        Latex.gfo  Precedence.gfo  PredefCnc.gfo  Prelude.gfo
```

**Comment by johnjcamilleri** [comment]
Two things are happening here. Firstly, all the following modules in `api` need to be cloned:
- Try
- Symbolic
- Syntax
- Constructors
- Combinators

Secondly, the new language needs to be added in `Make.hs` (see definitions of `langs` at line 324) for the build script to know about it. After doing this manually, you get a meaningful error from GF rather than "no input files".

I'm not sure if these steps should be performed as part of `Clone.hs` or as a separate script, e.g. `AddLang.hs`. I will implement this now as part of Clone.hs, but can probably be easily convinced to factor them out separately.

**Comment by kristiank** [comment]
Thanks for clarifying, helping and implementing!
I sympathize with factoring out as a separate `AddLang.sh`, but then (for new users like me) it would be very nice if `Clone.hs` would say perhaps "no input files, has the language been added with AddLang.hs yet?" or something similar to connect these two actions.

**Comment by kristiank** [comment]
My scenario is to start with Votic by cloning Estonian. I have now manually cloning your specified modules in `api` and added Votic to `Make.hs`.

After rectifying some obvious replacements of `*Est` into `*Vot` I ran into this:
```bash
$ runghc Make build --langs=Vot
Building [prelude]
Building [AllTenses] src/*/All*.gf src/*/Symbol*.gf src/*/Compatibility*.gf src/api/Try*.gf src/api/Symbolic*.gf
/home/kristian/Projektid/Grammatical Framework/git/gf-rgl/src/abstract/Extra.gf:
    Warning: default encoding has changed from Latin-1 to UTF-8
None of these files exists:
  src/votic/CompatibilityVot.gf
  src/src/votic/CompatibilityVot.gf
Ran: gf -batch -gf-lib-path=src -s -no-pmcfg --gfo-dir=dist/alltenses src/votic/AllVot.gf src/votic/SymbolVot.gf src/votic/CompatibilityVot.gf src/api/TryVot.gf src/api/SymbolicVot.gf
gf exited with exit code: 1
```
I can't find any references to the Compatibility module either in the original Estonian sources nor in the cloned Votic sources nor in the `api` modules.

Do I need to and i that case how do I come up with the Compatibility module for my new language?

**Comment by johnjcamilleri** [comment]
I've made significant improvements to `Make.hs` so that it reads the language config from the file `languages.csv` and is clearer about what it's doing.
I also updated `src/Clone.hs` to copy the relevant files in `src/api` and also add the new language to the config file.

You can try it out with the following commands:
```
gf-rgl/src$ runghc Clone estonian votic Est Vot
gf-rgl/src$ cd ..
gf-rgl$ runghc Make build alltenses lang --langs=Vot
```

Two notes about the build command:
1. If you omit `alltenses`, it will try to build Votic with the `mkPresent` preprocessor, which it doesn't support.
2. If you omit `lang`, it will try to build `CompatibilityVot` which doesn't exist (and shouldn't be needed initially).

Alternatively you can just issue the "build everything" command:
```
gf-rgl$ runghc Make build
```
I realise this seems quirky, but it's the result of an inherited design decision which I'm not sure if I should change.
