### ISSUE TITLE
French grammar plural error

### ISSUE THREAD

**Issue by yuosef46** [GrammaticalFramework/gf-rgl#383]
Running the following code gives a wrong output:
```
mkPhr(mkUtt(mkNP (aPl_Det) (mkCN (francais_2_A) (film_1_N))))
```
output: des films françaiss
I checked DictFre, and it seems to be written fine, the problem seems to be within the French grammar.

**Comment by aarneranta** [comment]
Hi Yousef,


Thanks a lot for this error report! It turned out, as you suggest, that there was an error in the two-place mkA paradigm: it did not follow all the rules defined for regA and the one-place mkA. Now it has been fixed. The error was quite obvious in the code, so I guess that version of mkA had not been used often.


BTW, when I tried to recompile DictFre, I found that there were lots of entries that were ill-formed there, for instance, verbs that did not have expected infinitive endings. I commented them out and was eventually able to compile the file. But I wonder how you managed to do it?


DictFre had its last log message from 2013. It had been automatically generated, probably from some noisy source, and in some quick way. It should be seen as a high priority of those morphological dictionaries that need to be checked and revised.


Regards


  Aarne


________________________________
From: Yousef Almesbahi ***@***.***>
Sent: Monday, December 27, 2021 9:50:23 AM
To: GrammaticalFramework/gf-rgl
Cc: Subscribed
Subject: [GrammaticalFramework/gf-rgl] French grammar plural error (Issue #383)


Running the following code gives a wrong output:

mkPhr(mkUtt(mkNP (aPl_Det) (mkCN (francais_2_A) (film_1_N))))



output: des films françaiss
I checked DictFre, and it seems to be written fine, the problem seems to be within the French grammar.
