### ISSUE TITLE
Spanish RGL missing inflection forms for adjectives

### ISSUE THREAD

**Issue by heatherleaf** [GrammaticalFramework/gf-rgl#57]
Someone told me that "bueno" is wrong in Spanish -- it should be "buen" in front of a noun. See e.g. this table (from Wiktionary):
![image](https://user-images.githubusercontent.com/1324196/47659627-a59dea80-db95-11e8-82a6-6220042393fb.png)

But it seems to me that the Spanish RGL doesn't have support for this:
```
> l -table good_A 
s Posit (AF Masc Sg) : bueno
s Posit (AF Masc Pl) : buenos
s Posit (AF Fem Sg) : buena
s Posit (AF Fem Pl) : buenas
s Posit AA : buenamente
s Compar (AF Masc Sg) : mejor
s Compar (AF Masc Pl) : mejores
s Compar (AF Fem Sg) : mejor
s Compar (AF Fem Pl) : mejores
s Compar AA : mejormente
s Superl (AF Masc Sg) : mejor
s Superl (AF Masc Pl) : mejores
s Superl (AF Fem Sg) : mejor
s Superl (AF Fem Pl) : mejores
s Superl AA : mejormente
```

Shouldn't there be an additional Bool argument to the AF constructor (telling whether the A is in front of a noun or stand-alone)?

I don't know Spanish myself, so probably there are better solutions

**Comment by odanoburu** [comment]
maybe this http://www.spanishdict.com/answers/281949/buen-amigo-or-amigo-bueno? not very good at Spanish, but I'd say it's the same in Portuguese

**Comment by inariksit** [comment]
@heatherleaf Yes, you're correct, this is an error in the GF RGL. I don't know if there is any better solution-- using `pre` for just this particular word? If followed by a word, not punctuation, then use "buen", otherwise "bueno"?
Anyway, this is how I did it in a foods grammar https://github.com/inariksit/GF-testing/blob/master/data/grammars/FoodsSpaBuen.gf#L49-L57 Can get leaner if you change the AForm parameter so that only Masc Sg forms take the additional parameter Attributive/Predicative.

**Comment by inariksit** [comment]
@odanoburu How about we look into this in the summer school, and check other Romance languages (that use the functor) as well? It shouldn't be a big thing to fix, but I'm just hesitant to get started because functors are complicated. :-P

**Comment by odanoburu** [comment]
@inariksit that would be great! `gftest` will come in handy to test all Romance languages!

**Comment by inariksit** [comment]
[dadcd38](https://github.com/GrammaticalFramework/gf-rgl/commit/dadcd386c99d6e52a5621a4b5dbbc994ebf88ee3) fixes this.
